version: '3.9'
services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    image: discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mynet
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile

    container_name: product-service
    image: product-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mynet
    depends_on:
      - discovery-service
  inventory-service:
    build:
      context: ./inventory-sevice
      dockerfile: Dockerfile
    container_name: inventory-service
    image: inventory-service:latest
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mynet
    depends_on:
      - discovery-service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    image: order-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mynet
    depends_on:
      - discovery-service
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"
  mysql-order:
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: "mysql-order"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order-service
    volumes:
      - ./mysql-order:/data/mysql
  mysql-inventory:
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3307:3307"
    container_name: "mysql-inventory"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inventory-service
    volumes:
      - ./inventory-order:/data/mysql
networks:
  mynet:
